{{- if or .Values.admission.enable (and .Values.controllerManager.enable (gt (int .Values.controllerManager.webhook.port) 0)) }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.admission.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
  name: kubeedge-admission-service
spec:
  ports:
    - port: 443
      protocol: TCP
      {{- if and .Values.controllerManager.enable (gt (int .Values.controllerManager.webhook.port) 0) }}
      targetPort: {{ .Values.controllerManager.webhook.port }}
      {{- else }}
      targetPort: 443
      {{- end }}
  selector:
  {{- if and .Values.controllerManager.enable (gt (int .Values.controllerManager.webhook.port) 0) }}
  {{- with .Values.controllerManager.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- with .Values.admission.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  sessionAffinity: None
{{- end }}
